CONF_VERIFY_SSL = "verify_ssl"
CONF_SERVICE_FILTER = "service_filter"
CONF_SERVICE_INCLUDE = "service_include"
CONF_SERVICE_EXCLUDE = "service_exclude"
CONF_HOST_INCLUDE = "host_include"
CONF_HOST_EXCLUDE = "host_exclude"
CONF_SELECTED_HOSTS = "selected_hosts"
CONF_SELECTED_SERVICES = "selected_services"
CONF_SELECTED_METRICS = "selected_metrics"
CONF_METRIC_INCLUDE = "metric_include"
CONF_METRIC_EXCLUDE = "metric_exclude"
"""Constantes pour l'intégration Checkmk"""
DOMAIN = "homeassistant_checkmk"
